"""Add image of post

Revision ID: bb543961212f
Revises: fc406d698d90
Create Date: 2023-04-27 16:17:44.453340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb543961212f'
down_revision = 'fc406d698d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Some content'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Some content'::character varying"))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
