"""Add themes to post

Revision ID: d46a2bb6df65
Revises: f1b21b1110e1
Create Date: 2023-05-29 19:30:36.907548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd46a2bb6df65'
down_revision = 'f1b21b1110e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'themes')
    # ### end Alembic commands ###
